Ratify bot-mode
ircv3/ircv3-specifications pull request #495
Opened 2022-04-12 20:29 UTC by progval

## Known implementations

Unchecked means incomplete or an intent to implement has been expressed. The numbers indicate minimum requirements. Any others?

### Server (2/2)

    * [x]  InspIRCd: (@SadieCat ) ircs://testnet.inspircd.org:6697
    * [x]  IRCCloud client (@jwheare)
    * [x]  oragono (@DanielOaks) ircs://testnet.oragono.io:6697

### Client (2/1)

    * [x]  IRCCloud (@jwheare)
    * [x]  Goguma (@emersion)

### Bouncer

 None

### Bots

    * [x] Limnoria (@progval)

### Networks

    * [x]  https://ergo.chat

2022-04-12 21:09 UTC, dgw commented
Sopel implements both the mode (sopel-irc/sopel#2088) and tag (sopel-irc/sopel#2089).

Yes, it accepts the unprefixed tag. Figured this spec would be ratified long before we made it to release, and it seems I'm about to be proven correct.

2022-04-13 20:27 UTC, SadieCat commented
I can push my support for this the moment its ratified. 👍🏻

2022-04-15 12:05 UTC, kylef approved these changes

2022-04-22 11:55 UTC, SadieCat commented
Is there any objections to ratifying this? I'd like it if I could get our implementation into InspIRCd v3.13.0 which is due to be released next Friday.

2022-04-25 17:41 UTC, jwheare commented
There was an objection raised in IRC from solanum/libera staff. As I understand it, they felt that IRCv3 shouldn't be pursuing specs that feel like a stop gap for a true metadata implementation.

This spec doesn't define a mechanism for keeping up to date with a change in a user's bot status other than periodic WHOIS or WHO polling. True metadata notifications on status changes would allow clients to keep member lists in sync.

In reality, a real bot is unlikely to ever change status, so I feel like running an initial WHO check on channel join and checking for the tag on new user JOINs should be sufficient for the vast majority of use cases.

There are outstanding issues with PMs when no shared channel exists, but those issues extend to many other things, and a future METADATA spec won't necessarily cater to that situation either.

I acknowledge and agree that effort should be spent on reviving a true metadata spec, so that we can focus in that direction for future cosmetic user status things, . But I think for this specific spec, where there is prior art for non-standard mode/whois numerics indicating bot status, and we have a broad consensus of implementation, we should ratify this.

It might be worth mentioning the prior art in the spec, similar to the Motivation section in the SETNAME spec: https://ircv3.net/specs/extensions/setname.html#motivation

See initial discussion here: https://github.com/ircv3/ircv3-ideas/issues/43

2022-04-26 11:41 UTC, jwheare requested changes
How's this?

2022-04-26 11:41 UTC, jwheare commented on extensions/bot-mode.md
>  This is a standardised mode that lets clients mark themselves as bots, and lets other clients see them as bots.
```suggestion
This specification defines a standardised mechanism to allow clients to mark themselves as bots.

## Motivation
This functionality was previously implemented by several IRC servers in independent ways using fixed mode letters and conflicting WHOIS numerics. This specification seeks to standardise the functionality, adding a message tag for increased visibility of bot status and an ISUPPORT token to allow for more flexible implementations.
```

2022-04-26 15:53 UTC, merged

2022-04-26 15:54 UTC, jwheare commented
Thanks for feedback and implementations all.